version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to docker.io...
      - echo $USERNAME
      - echo $PASSWORD
      
  build:
    commands:
      - echo Building the Docker image...
      - docker build -f Dockerfile -t $REPOSITORY_URI -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI
      - printf '[{"name":"awsdevops","imageUri":"%s"}]' $REPOSITORY_URI > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
