version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to docker.io...
      - echo $USERNAME
      - echo $PASSWORD
      - docker login -u $USERNAME -p $PASSWORD
      
      
  build:
    commands:
      - echo Building the Docker image...
      - docker build -f Dockerfile -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      
artifacts:
    files: imagedefinitions.json
